//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STTSoft.STTSoftService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AccountDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccRoleField;
        
        private System.Nullable<int> AccLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccPassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccRole {
            get {
                return this.AccRoleField;
            }
            set {
                if ((object.ReferenceEquals(this.AccRoleField, value) != true)) {
                    this.AccRoleField = value;
                    this.RaisePropertyChanged("AccRole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<int> AccLevel {
            get {
                return this.AccLevelField;
            }
            set {
                if ((this.AccLevelField.Equals(value) != true)) {
                    this.AccLevelField = value;
                    this.RaisePropertyChanged("AccLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AccMail {
            get {
                return this.AccMailField;
            }
            set {
                if ((object.ReferenceEquals(this.AccMailField, value) != true)) {
                    this.AccMailField = value;
                    this.RaisePropertyChanged("AccMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AccPhone {
            get {
                return this.AccPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.AccPhoneField, value) != true)) {
                    this.AccPhoneField = value;
                    this.RaisePropertyChanged("AccPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AccPass {
            get {
                return this.AccPassField;
            }
            set {
                if ((object.ReferenceEquals(this.AccPassField, value) != true)) {
                    this.AccPassField = value;
                    this.RaisePropertyChanged("AccPass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AccName {
            get {
                return this.AccNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccNameField, value) != true)) {
                    this.AccNameField = value;
                    this.RaisePropertyChanged("AccName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProductDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProImageField;
        
        private double ProPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProId {
            get {
                return this.ProIdField;
            }
            set {
                if ((this.ProIdField.Equals(value) != true)) {
                    this.ProIdField = value;
                    this.RaisePropertyChanged("ProId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProName {
            get {
                return this.ProNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProNameField, value) != true)) {
                    this.ProNameField = value;
                    this.RaisePropertyChanged("ProName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ProDetail {
            get {
                return this.ProDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.ProDetailField, value) != true)) {
                    this.ProDetailField = value;
                    this.RaisePropertyChanged("ProDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ProImage {
            get {
                return this.ProImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ProImageField, value) != true)) {
                    this.ProImageField = value;
                    this.RaisePropertyChanged("ProImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double ProPrice {
            get {
                return this.ProPriceField;
            }
            set {
                if ((this.ProPriceField.Equals(value) != true)) {
                    this.ProPriceField = value;
                    this.RaisePropertyChanged("ProPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CategoryDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CatIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CatNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CatId {
            get {
                return this.CatIdField;
            }
            set {
                if ((this.CatIdField.Equals(value) != true)) {
                    this.CatIdField = value;
                    this.RaisePropertyChanged("CatId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CatName {
            get {
                return this.CatNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CatNameField, value) != true)) {
                    this.CatNameField = value;
                    this.RaisePropertyChanged("CatName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="STTSoftService.AdminServiceSoap")]
    public interface AdminServiceSoap {
        
        // CODEGEN: Generating message contract since element name AccountListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccountList", ReplyAction="*")]
        STTSoft.STTSoftService.AccountListResponse AccountList(STTSoft.STTSoftService.AccountListRequest request);
        
        // CODEGEN: Generating message contract since element name accName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccountInsert", ReplyAction="*")]
        STTSoft.STTSoftService.AccountInsertResponse AccountInsert(STTSoft.STTSoftService.AccountInsertRequest request);
        
        // CODEGEN: Generating message contract since element name accName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccountEdit", ReplyAction="*")]
        STTSoft.STTSoftService.AccountEditResponse AccountEdit(STTSoft.STTSoftService.AccountEditRequest request);
        
        // CODEGEN: Generating message contract since element name accName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccountDelete", ReplyAction="*")]
        STTSoft.STTSoftService.AccountDeleteResponse AccountDelete(STTSoft.STTSoftService.AccountDeleteRequest request);
        
        // CODEGEN: Generating message contract since element name ProductListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProductList", ReplyAction="*")]
        STTSoft.STTSoftService.ProductListResponse ProductList(STTSoft.STTSoftService.ProductListRequest request);
        
        // CODEGEN: Generating message contract since element name proName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProductInsert", ReplyAction="*")]
        STTSoft.STTSoftService.ProductInsertResponse ProductInsert(STTSoft.STTSoftService.ProductInsertRequest request);
        
        // CODEGEN: Generating message contract since element name proName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProductEdit", ReplyAction="*")]
        STTSoft.STTSoftService.ProductEditResponse ProductEdit(STTSoft.STTSoftService.ProductEditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProductDelete", ReplyAction="*")]
        bool ProductDelete(int proId);
        
        // CODEGEN: Generating message contract since element name CatalogListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CatalogList", ReplyAction="*")]
        STTSoft.STTSoftService.CatalogListResponse CatalogList(STTSoft.STTSoftService.CatalogListRequest request);
        
        // CODEGEN: Generating message contract since element name catName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CatalogInsert", ReplyAction="*")]
        STTSoft.STTSoftService.CatalogInsertResponse CatalogInsert(STTSoft.STTSoftService.CatalogInsertRequest request);
        
        // CODEGEN: Generating message contract since element name catName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CatalogEdit", ReplyAction="*")]
        STTSoft.STTSoftService.CatalogEditResponse CatalogEdit(STTSoft.STTSoftService.CatalogEditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CatalogDelete", ReplyAction="*")]
        bool CatalogDelete(int catId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccountList", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.AccountListRequestBody Body;
        
        public AccountListRequest() {
        }
        
        public AccountListRequest(STTSoft.STTSoftService.AccountListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AccountListRequestBody {
        
        public AccountListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccountListResponse", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.AccountListResponseBody Body;
        
        public AccountListResponse() {
        }
        
        public AccountListResponse(STTSoft.STTSoftService.AccountListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public STTSoft.STTSoftService.AccountDTO[] AccountListResult;
        
        public AccountListResponseBody() {
        }
        
        public AccountListResponseBody(STTSoft.STTSoftService.AccountDTO[] AccountListResult) {
            this.AccountListResult = AccountListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountInsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccountInsert", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.AccountInsertRequestBody Body;
        
        public AccountInsertRequest() {
        }
        
        public AccountInsertRequest(STTSoft.STTSoftService.AccountInsertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountInsertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string accRole;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int accLevel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string accMail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string accPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string accPass;
        
        public AccountInsertRequestBody() {
        }
        
        public AccountInsertRequestBody(string accName, string accRole, int accLevel, string accMail, string accPhone, string accPass) {
            this.accName = accName;
            this.accRole = accRole;
            this.accLevel = accLevel;
            this.accMail = accMail;
            this.accPhone = accPhone;
            this.accPass = accPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountInsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccountInsertResponse", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.AccountInsertResponseBody Body;
        
        public AccountInsertResponse() {
        }
        
        public AccountInsertResponse(STTSoft.STTSoftService.AccountInsertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountInsertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AccountInsertResult;
        
        public AccountInsertResponseBody() {
        }
        
        public AccountInsertResponseBody(bool AccountInsertResult) {
            this.AccountInsertResult = AccountInsertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountEditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccountEdit", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.AccountEditRequestBody Body;
        
        public AccountEditRequest() {
        }
        
        public AccountEditRequest(STTSoft.STTSoftService.AccountEditRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountEditRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string accRole;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int accLevel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string accMail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string accPhone;
        
        public AccountEditRequestBody() {
        }
        
        public AccountEditRequestBody(string accName, string accRole, int accLevel, string accMail, string accPhone) {
            this.accName = accName;
            this.accRole = accRole;
            this.accLevel = accLevel;
            this.accMail = accMail;
            this.accPhone = accPhone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountEditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccountEditResponse", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.AccountEditResponseBody Body;
        
        public AccountEditResponse() {
        }
        
        public AccountEditResponse(STTSoft.STTSoftService.AccountEditResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountEditResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AccountEditResult;
        
        public AccountEditResponseBody() {
        }
        
        public AccountEditResponseBody(bool AccountEditResult) {
            this.AccountEditResult = AccountEditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountDeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccountDelete", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.AccountDeleteRequestBody Body;
        
        public AccountDeleteRequest() {
        }
        
        public AccountDeleteRequest(STTSoft.STTSoftService.AccountDeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountDeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accName;
        
        public AccountDeleteRequestBody() {
        }
        
        public AccountDeleteRequestBody(string accName) {
            this.accName = accName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountDeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccountDeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.AccountDeleteResponseBody Body;
        
        public AccountDeleteResponse() {
        }
        
        public AccountDeleteResponse(STTSoft.STTSoftService.AccountDeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountDeleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AccountDeleteResult;
        
        public AccountDeleteResponseBody() {
        }
        
        public AccountDeleteResponseBody(bool AccountDeleteResult) {
            this.AccountDeleteResult = AccountDeleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProductListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProductList", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.ProductListRequestBody Body;
        
        public ProductListRequest() {
        }
        
        public ProductListRequest(STTSoft.STTSoftService.ProductListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ProductListRequestBody {
        
        public ProductListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProductListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProductListResponse", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.ProductListResponseBody Body;
        
        public ProductListResponse() {
        }
        
        public ProductListResponse(STTSoft.STTSoftService.ProductListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public STTSoft.STTSoftService.ProductDTO[] ProductListResult;
        
        public ProductListResponseBody() {
        }
        
        public ProductListResponseBody(STTSoft.STTSoftService.ProductDTO[] ProductListResult) {
            this.ProductListResult = ProductListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProductInsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProductInsert", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.ProductInsertRequestBody Body;
        
        public ProductInsertRequest() {
        }
        
        public ProductInsertRequest(STTSoft.STTSoftService.ProductInsertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductInsertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string proName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string proDetail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string proImage;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double proPrice;
        
        public ProductInsertRequestBody() {
        }
        
        public ProductInsertRequestBody(string proName, string proDetail, string proImage, double proPrice) {
            this.proName = proName;
            this.proDetail = proDetail;
            this.proImage = proImage;
            this.proPrice = proPrice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProductInsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProductInsertResponse", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.ProductInsertResponseBody Body;
        
        public ProductInsertResponse() {
        }
        
        public ProductInsertResponse(STTSoft.STTSoftService.ProductInsertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductInsertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ProductInsertResult;
        
        public ProductInsertResponseBody() {
        }
        
        public ProductInsertResponseBody(bool ProductInsertResult) {
            this.ProductInsertResult = ProductInsertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProductEditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProductEdit", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.ProductEditRequestBody Body;
        
        public ProductEditRequest() {
        }
        
        public ProductEditRequest(STTSoft.STTSoftService.ProductEditRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductEditRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int proId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string proName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string proDetail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string proImage;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double proPrice;
        
        public ProductEditRequestBody() {
        }
        
        public ProductEditRequestBody(int proId, string proName, string proDetail, string proImage, double proPrice) {
            this.proId = proId;
            this.proName = proName;
            this.proDetail = proDetail;
            this.proImage = proImage;
            this.proPrice = proPrice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProductEditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProductEditResponse", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.ProductEditResponseBody Body;
        
        public ProductEditResponse() {
        }
        
        public ProductEditResponse(STTSoft.STTSoftService.ProductEditResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductEditResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ProductEditResult;
        
        public ProductEditResponseBody() {
        }
        
        public ProductEditResponseBody(bool ProductEditResult) {
            this.ProductEditResult = ProductEditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CatalogListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CatalogList", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.CatalogListRequestBody Body;
        
        public CatalogListRequest() {
        }
        
        public CatalogListRequest(STTSoft.STTSoftService.CatalogListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CatalogListRequestBody {
        
        public CatalogListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CatalogListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CatalogListResponse", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.CatalogListResponseBody Body;
        
        public CatalogListResponse() {
        }
        
        public CatalogListResponse(STTSoft.STTSoftService.CatalogListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CatalogListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public STTSoft.STTSoftService.CategoryDTO[] CatalogListResult;
        
        public CatalogListResponseBody() {
        }
        
        public CatalogListResponseBody(STTSoft.STTSoftService.CategoryDTO[] CatalogListResult) {
            this.CatalogListResult = CatalogListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CatalogInsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CatalogInsert", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.CatalogInsertRequestBody Body;
        
        public CatalogInsertRequest() {
        }
        
        public CatalogInsertRequest(STTSoft.STTSoftService.CatalogInsertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CatalogInsertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string catName;
        
        public CatalogInsertRequestBody() {
        }
        
        public CatalogInsertRequestBody(string catName) {
            this.catName = catName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CatalogInsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CatalogInsertResponse", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.CatalogInsertResponseBody Body;
        
        public CatalogInsertResponse() {
        }
        
        public CatalogInsertResponse(STTSoft.STTSoftService.CatalogInsertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CatalogInsertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CatalogInsertResult;
        
        public CatalogInsertResponseBody() {
        }
        
        public CatalogInsertResponseBody(bool CatalogInsertResult) {
            this.CatalogInsertResult = CatalogInsertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CatalogEditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CatalogEdit", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.CatalogEditRequestBody Body;
        
        public CatalogEditRequest() {
        }
        
        public CatalogEditRequest(STTSoft.STTSoftService.CatalogEditRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CatalogEditRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int catId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string catName;
        
        public CatalogEditRequestBody() {
        }
        
        public CatalogEditRequestBody(int catId, string catName) {
            this.catId = catId;
            this.catName = catName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CatalogEditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CatalogEditResponse", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.CatalogEditResponseBody Body;
        
        public CatalogEditResponse() {
        }
        
        public CatalogEditResponse(STTSoft.STTSoftService.CatalogEditResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CatalogEditResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CatalogEditResult;
        
        public CatalogEditResponseBody() {
        }
        
        public CatalogEditResponseBody(bool CatalogEditResult) {
            this.CatalogEditResult = CatalogEditResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdminServiceSoapChannel : STTSoft.STTSoftService.AdminServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceSoapClient : System.ServiceModel.ClientBase<STTSoft.STTSoftService.AdminServiceSoap>, STTSoft.STTSoftService.AdminServiceSoap {
        
        public AdminServiceSoapClient() {
        }
        
        public AdminServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STTSoft.STTSoftService.AccountListResponse STTSoft.STTSoftService.AdminServiceSoap.AccountList(STTSoft.STTSoftService.AccountListRequest request) {
            return base.Channel.AccountList(request);
        }
        
        public STTSoft.STTSoftService.AccountDTO[] AccountList() {
            STTSoft.STTSoftService.AccountListRequest inValue = new STTSoft.STTSoftService.AccountListRequest();
            inValue.Body = new STTSoft.STTSoftService.AccountListRequestBody();
            STTSoft.STTSoftService.AccountListResponse retVal = ((STTSoft.STTSoftService.AdminServiceSoap)(this)).AccountList(inValue);
            return retVal.Body.AccountListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STTSoft.STTSoftService.AccountInsertResponse STTSoft.STTSoftService.AdminServiceSoap.AccountInsert(STTSoft.STTSoftService.AccountInsertRequest request) {
            return base.Channel.AccountInsert(request);
        }
        
        public bool AccountInsert(string accName, string accRole, int accLevel, string accMail, string accPhone, string accPass) {
            STTSoft.STTSoftService.AccountInsertRequest inValue = new STTSoft.STTSoftService.AccountInsertRequest();
            inValue.Body = new STTSoft.STTSoftService.AccountInsertRequestBody();
            inValue.Body.accName = accName;
            inValue.Body.accRole = accRole;
            inValue.Body.accLevel = accLevel;
            inValue.Body.accMail = accMail;
            inValue.Body.accPhone = accPhone;
            inValue.Body.accPass = accPass;
            STTSoft.STTSoftService.AccountInsertResponse retVal = ((STTSoft.STTSoftService.AdminServiceSoap)(this)).AccountInsert(inValue);
            return retVal.Body.AccountInsertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STTSoft.STTSoftService.AccountEditResponse STTSoft.STTSoftService.AdminServiceSoap.AccountEdit(STTSoft.STTSoftService.AccountEditRequest request) {
            return base.Channel.AccountEdit(request);
        }
        
        public bool AccountEdit(string accName, string accRole, int accLevel, string accMail, string accPhone) {
            STTSoft.STTSoftService.AccountEditRequest inValue = new STTSoft.STTSoftService.AccountEditRequest();
            inValue.Body = new STTSoft.STTSoftService.AccountEditRequestBody();
            inValue.Body.accName = accName;
            inValue.Body.accRole = accRole;
            inValue.Body.accLevel = accLevel;
            inValue.Body.accMail = accMail;
            inValue.Body.accPhone = accPhone;
            STTSoft.STTSoftService.AccountEditResponse retVal = ((STTSoft.STTSoftService.AdminServiceSoap)(this)).AccountEdit(inValue);
            return retVal.Body.AccountEditResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STTSoft.STTSoftService.AccountDeleteResponse STTSoft.STTSoftService.AdminServiceSoap.AccountDelete(STTSoft.STTSoftService.AccountDeleteRequest request) {
            return base.Channel.AccountDelete(request);
        }
        
        public bool AccountDelete(string accName) {
            STTSoft.STTSoftService.AccountDeleteRequest inValue = new STTSoft.STTSoftService.AccountDeleteRequest();
            inValue.Body = new STTSoft.STTSoftService.AccountDeleteRequestBody();
            inValue.Body.accName = accName;
            STTSoft.STTSoftService.AccountDeleteResponse retVal = ((STTSoft.STTSoftService.AdminServiceSoap)(this)).AccountDelete(inValue);
            return retVal.Body.AccountDeleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STTSoft.STTSoftService.ProductListResponse STTSoft.STTSoftService.AdminServiceSoap.ProductList(STTSoft.STTSoftService.ProductListRequest request) {
            return base.Channel.ProductList(request);
        }
        
        public STTSoft.STTSoftService.ProductDTO[] ProductList() {
            STTSoft.STTSoftService.ProductListRequest inValue = new STTSoft.STTSoftService.ProductListRequest();
            inValue.Body = new STTSoft.STTSoftService.ProductListRequestBody();
            STTSoft.STTSoftService.ProductListResponse retVal = ((STTSoft.STTSoftService.AdminServiceSoap)(this)).ProductList(inValue);
            return retVal.Body.ProductListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STTSoft.STTSoftService.ProductInsertResponse STTSoft.STTSoftService.AdminServiceSoap.ProductInsert(STTSoft.STTSoftService.ProductInsertRequest request) {
            return base.Channel.ProductInsert(request);
        }
        
        public bool ProductInsert(string proName, string proDetail, string proImage, double proPrice) {
            STTSoft.STTSoftService.ProductInsertRequest inValue = new STTSoft.STTSoftService.ProductInsertRequest();
            inValue.Body = new STTSoft.STTSoftService.ProductInsertRequestBody();
            inValue.Body.proName = proName;
            inValue.Body.proDetail = proDetail;
            inValue.Body.proImage = proImage;
            inValue.Body.proPrice = proPrice;
            STTSoft.STTSoftService.ProductInsertResponse retVal = ((STTSoft.STTSoftService.AdminServiceSoap)(this)).ProductInsert(inValue);
            return retVal.Body.ProductInsertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STTSoft.STTSoftService.ProductEditResponse STTSoft.STTSoftService.AdminServiceSoap.ProductEdit(STTSoft.STTSoftService.ProductEditRequest request) {
            return base.Channel.ProductEdit(request);
        }
        
        public bool ProductEdit(int proId, string proName, string proDetail, string proImage, double proPrice) {
            STTSoft.STTSoftService.ProductEditRequest inValue = new STTSoft.STTSoftService.ProductEditRequest();
            inValue.Body = new STTSoft.STTSoftService.ProductEditRequestBody();
            inValue.Body.proId = proId;
            inValue.Body.proName = proName;
            inValue.Body.proDetail = proDetail;
            inValue.Body.proImage = proImage;
            inValue.Body.proPrice = proPrice;
            STTSoft.STTSoftService.ProductEditResponse retVal = ((STTSoft.STTSoftService.AdminServiceSoap)(this)).ProductEdit(inValue);
            return retVal.Body.ProductEditResult;
        }
        
        public bool ProductDelete(int proId) {
            return base.Channel.ProductDelete(proId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STTSoft.STTSoftService.CatalogListResponse STTSoft.STTSoftService.AdminServiceSoap.CatalogList(STTSoft.STTSoftService.CatalogListRequest request) {
            return base.Channel.CatalogList(request);
        }
        
        public STTSoft.STTSoftService.CategoryDTO[] CatalogList() {
            STTSoft.STTSoftService.CatalogListRequest inValue = new STTSoft.STTSoftService.CatalogListRequest();
            inValue.Body = new STTSoft.STTSoftService.CatalogListRequestBody();
            STTSoft.STTSoftService.CatalogListResponse retVal = ((STTSoft.STTSoftService.AdminServiceSoap)(this)).CatalogList(inValue);
            return retVal.Body.CatalogListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STTSoft.STTSoftService.CatalogInsertResponse STTSoft.STTSoftService.AdminServiceSoap.CatalogInsert(STTSoft.STTSoftService.CatalogInsertRequest request) {
            return base.Channel.CatalogInsert(request);
        }
        
        public bool CatalogInsert(string catName) {
            STTSoft.STTSoftService.CatalogInsertRequest inValue = new STTSoft.STTSoftService.CatalogInsertRequest();
            inValue.Body = new STTSoft.STTSoftService.CatalogInsertRequestBody();
            inValue.Body.catName = catName;
            STTSoft.STTSoftService.CatalogInsertResponse retVal = ((STTSoft.STTSoftService.AdminServiceSoap)(this)).CatalogInsert(inValue);
            return retVal.Body.CatalogInsertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STTSoft.STTSoftService.CatalogEditResponse STTSoft.STTSoftService.AdminServiceSoap.CatalogEdit(STTSoft.STTSoftService.CatalogEditRequest request) {
            return base.Channel.CatalogEdit(request);
        }
        
        public bool CatalogEdit(int catId, string catName) {
            STTSoft.STTSoftService.CatalogEditRequest inValue = new STTSoft.STTSoftService.CatalogEditRequest();
            inValue.Body = new STTSoft.STTSoftService.CatalogEditRequestBody();
            inValue.Body.catId = catId;
            inValue.Body.catName = catName;
            STTSoft.STTSoftService.CatalogEditResponse retVal = ((STTSoft.STTSoftService.AdminServiceSoap)(this)).CatalogEdit(inValue);
            return retVal.Body.CatalogEditResult;
        }
        
        public bool CatalogDelete(int catId) {
            return base.Channel.CatalogDelete(catId);
        }
    }
}
