//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STTSoft.STTSoftService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AccountDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccRoleField;
        
        private System.Nullable<int> AccLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccPassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccRole {
            get {
                return this.AccRoleField;
            }
            set {
                if ((object.ReferenceEquals(this.AccRoleField, value) != true)) {
                    this.AccRoleField = value;
                    this.RaisePropertyChanged("AccRole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<int> AccLevel {
            get {
                return this.AccLevelField;
            }
            set {
                if ((this.AccLevelField.Equals(value) != true)) {
                    this.AccLevelField = value;
                    this.RaisePropertyChanged("AccLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AccMail {
            get {
                return this.AccMailField;
            }
            set {
                if ((object.ReferenceEquals(this.AccMailField, value) != true)) {
                    this.AccMailField = value;
                    this.RaisePropertyChanged("AccMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AccPhone {
            get {
                return this.AccPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.AccPhoneField, value) != true)) {
                    this.AccPhoneField = value;
                    this.RaisePropertyChanged("AccPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AccPass {
            get {
                return this.AccPassField;
            }
            set {
                if ((object.ReferenceEquals(this.AccPassField, value) != true)) {
                    this.AccPassField = value;
                    this.RaisePropertyChanged("AccPass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AccName {
            get {
                return this.AccNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccNameField, value) != true)) {
                    this.AccNameField = value;
                    this.RaisePropertyChanged("AccName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="STTSoftService.AdminServiceSoap")]
    public interface AdminServiceSoap {
        
        // CODEGEN: Generating message contract since element name AccountListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccountList", ReplyAction="*")]
        STTSoft.STTSoftService.AccountListResponse AccountList(STTSoft.STTSoftService.AccountListRequest request);
        
        // CODEGEN: Generating message contract since element name accName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccountInsert", ReplyAction="*")]
        STTSoft.STTSoftService.AccountInsertResponse AccountInsert(STTSoft.STTSoftService.AccountInsertRequest request);
        
        // CODEGEN: Generating message contract since element name accName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccountEdit", ReplyAction="*")]
        STTSoft.STTSoftService.AccountEditResponse AccountEdit(STTSoft.STTSoftService.AccountEditRequest request);
        
        // CODEGEN: Generating message contract since element name accName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccountDelete", ReplyAction="*")]
        STTSoft.STTSoftService.AccountDeleteResponse AccountDelete(STTSoft.STTSoftService.AccountDeleteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccountList", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.AccountListRequestBody Body;
        
        public AccountListRequest() {
        }
        
        public AccountListRequest(STTSoft.STTSoftService.AccountListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AccountListRequestBody {
        
        public AccountListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccountListResponse", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.AccountListResponseBody Body;
        
        public AccountListResponse() {
        }
        
        public AccountListResponse(STTSoft.STTSoftService.AccountListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public STTSoft.STTSoftService.AccountDTO[] AccountListResult;
        
        public AccountListResponseBody() {
        }
        
        public AccountListResponseBody(STTSoft.STTSoftService.AccountDTO[] AccountListResult) {
            this.AccountListResult = AccountListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountInsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccountInsert", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.AccountInsertRequestBody Body;
        
        public AccountInsertRequest() {
        }
        
        public AccountInsertRequest(STTSoft.STTSoftService.AccountInsertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountInsertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string accRole;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int accLevel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string accMail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string accPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string accPass;
        
        public AccountInsertRequestBody() {
        }
        
        public AccountInsertRequestBody(string accName, string accRole, int accLevel, string accMail, string accPhone, string accPass) {
            this.accName = accName;
            this.accRole = accRole;
            this.accLevel = accLevel;
            this.accMail = accMail;
            this.accPhone = accPhone;
            this.accPass = accPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountInsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccountInsertResponse", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.AccountInsertResponseBody Body;
        
        public AccountInsertResponse() {
        }
        
        public AccountInsertResponse(STTSoft.STTSoftService.AccountInsertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountInsertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AccountInsertResult;
        
        public AccountInsertResponseBody() {
        }
        
        public AccountInsertResponseBody(bool AccountInsertResult) {
            this.AccountInsertResult = AccountInsertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountEditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccountEdit", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.AccountEditRequestBody Body;
        
        public AccountEditRequest() {
        }
        
        public AccountEditRequest(STTSoft.STTSoftService.AccountEditRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountEditRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string accRole;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int accLevel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string accMail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string accPhone;
        
        public AccountEditRequestBody() {
        }
        
        public AccountEditRequestBody(string accName, string accRole, int accLevel, string accMail, string accPhone) {
            this.accName = accName;
            this.accRole = accRole;
            this.accLevel = accLevel;
            this.accMail = accMail;
            this.accPhone = accPhone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountEditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccountEditResponse", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.AccountEditResponseBody Body;
        
        public AccountEditResponse() {
        }
        
        public AccountEditResponse(STTSoft.STTSoftService.AccountEditResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountEditResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AccountEditResult;
        
        public AccountEditResponseBody() {
        }
        
        public AccountEditResponseBody(bool AccountEditResult) {
            this.AccountEditResult = AccountEditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountDeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccountDelete", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.AccountDeleteRequestBody Body;
        
        public AccountDeleteRequest() {
        }
        
        public AccountDeleteRequest(STTSoft.STTSoftService.AccountDeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountDeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accName;
        
        public AccountDeleteRequestBody() {
        }
        
        public AccountDeleteRequestBody(string accName) {
            this.accName = accName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountDeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccountDeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.AccountDeleteResponseBody Body;
        
        public AccountDeleteResponse() {
        }
        
        public AccountDeleteResponse(STTSoft.STTSoftService.AccountDeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountDeleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AccountDeleteResult;
        
        public AccountDeleteResponseBody() {
        }
        
        public AccountDeleteResponseBody(bool AccountDeleteResult) {
            this.AccountDeleteResult = AccountDeleteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdminServiceSoapChannel : STTSoft.STTSoftService.AdminServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceSoapClient : System.ServiceModel.ClientBase<STTSoft.STTSoftService.AdminServiceSoap>, STTSoft.STTSoftService.AdminServiceSoap {
        
        public AdminServiceSoapClient() {
        }
        
        public AdminServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STTSoft.STTSoftService.AccountListResponse STTSoft.STTSoftService.AdminServiceSoap.AccountList(STTSoft.STTSoftService.AccountListRequest request) {
            return base.Channel.AccountList(request);
        }
        
        public STTSoft.STTSoftService.AccountDTO[] AccountList() {
            STTSoft.STTSoftService.AccountListRequest inValue = new STTSoft.STTSoftService.AccountListRequest();
            inValue.Body = new STTSoft.STTSoftService.AccountListRequestBody();
            STTSoft.STTSoftService.AccountListResponse retVal = ((STTSoft.STTSoftService.AdminServiceSoap)(this)).AccountList(inValue);
            return retVal.Body.AccountListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STTSoft.STTSoftService.AccountInsertResponse STTSoft.STTSoftService.AdminServiceSoap.AccountInsert(STTSoft.STTSoftService.AccountInsertRequest request) {
            return base.Channel.AccountInsert(request);
        }
        
        public bool AccountInsert(string accName, string accRole, int accLevel, string accMail, string accPhone, string accPass) {
            STTSoft.STTSoftService.AccountInsertRequest inValue = new STTSoft.STTSoftService.AccountInsertRequest();
            inValue.Body = new STTSoft.STTSoftService.AccountInsertRequestBody();
            inValue.Body.accName = accName;
            inValue.Body.accRole = accRole;
            inValue.Body.accLevel = accLevel;
            inValue.Body.accMail = accMail;
            inValue.Body.accPhone = accPhone;
            inValue.Body.accPass = accPass;
            STTSoft.STTSoftService.AccountInsertResponse retVal = ((STTSoft.STTSoftService.AdminServiceSoap)(this)).AccountInsert(inValue);
            return retVal.Body.AccountInsertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STTSoft.STTSoftService.AccountEditResponse STTSoft.STTSoftService.AdminServiceSoap.AccountEdit(STTSoft.STTSoftService.AccountEditRequest request) {
            return base.Channel.AccountEdit(request);
        }
        
        public bool AccountEdit(string accName, string accRole, int accLevel, string accMail, string accPhone) {
            STTSoft.STTSoftService.AccountEditRequest inValue = new STTSoft.STTSoftService.AccountEditRequest();
            inValue.Body = new STTSoft.STTSoftService.AccountEditRequestBody();
            inValue.Body.accName = accName;
            inValue.Body.accRole = accRole;
            inValue.Body.accLevel = accLevel;
            inValue.Body.accMail = accMail;
            inValue.Body.accPhone = accPhone;
            STTSoft.STTSoftService.AccountEditResponse retVal = ((STTSoft.STTSoftService.AdminServiceSoap)(this)).AccountEdit(inValue);
            return retVal.Body.AccountEditResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STTSoft.STTSoftService.AccountDeleteResponse STTSoft.STTSoftService.AdminServiceSoap.AccountDelete(STTSoft.STTSoftService.AccountDeleteRequest request) {
            return base.Channel.AccountDelete(request);
        }
        
        public bool AccountDelete(string accName) {
            STTSoft.STTSoftService.AccountDeleteRequest inValue = new STTSoft.STTSoftService.AccountDeleteRequest();
            inValue.Body = new STTSoft.STTSoftService.AccountDeleteRequestBody();
            inValue.Body.accName = accName;
            STTSoft.STTSoftService.AccountDeleteResponse retVal = ((STTSoft.STTSoftService.AdminServiceSoap)(this)).AccountDelete(inValue);
            return retVal.Body.AccountDeleteResult;
        }
    }
}
