//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STTSoft.STTSoftService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccRoleField;
        
        private System.Nullable<int> AccLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccPassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private STTSoft.STTSoftService.Bank BankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private STTSoft.STTSoftService.Order[] OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private STTSoft.STTSoftService.Discount DiscountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccName {
            get {
                return this.AccNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccNameField, value) != true)) {
                    this.AccNameField = value;
                    this.RaisePropertyChanged("AccName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccRole {
            get {
                return this.AccRoleField;
            }
            set {
                if ((object.ReferenceEquals(this.AccRoleField, value) != true)) {
                    this.AccRoleField = value;
                    this.RaisePropertyChanged("AccRole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> AccLevel {
            get {
                return this.AccLevelField;
            }
            set {
                if ((this.AccLevelField.Equals(value) != true)) {
                    this.AccLevelField = value;
                    this.RaisePropertyChanged("AccLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AccMail {
            get {
                return this.AccMailField;
            }
            set {
                if ((object.ReferenceEquals(this.AccMailField, value) != true)) {
                    this.AccMailField = value;
                    this.RaisePropertyChanged("AccMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AccPhone {
            get {
                return this.AccPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.AccPhoneField, value) != true)) {
                    this.AccPhoneField = value;
                    this.RaisePropertyChanged("AccPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AccPass {
            get {
                return this.AccPassField;
            }
            set {
                if ((object.ReferenceEquals(this.AccPassField, value) != true)) {
                    this.AccPassField = value;
                    this.RaisePropertyChanged("AccPass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public STTSoft.STTSoftService.Bank Bank {
            get {
                return this.BankField;
            }
            set {
                if ((object.ReferenceEquals(this.BankField, value) != true)) {
                    this.BankField = value;
                    this.RaisePropertyChanged("Bank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public STTSoft.STTSoftService.Order[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public STTSoft.STTSoftService.Discount Discount {
            get {
                return this.DiscountField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscountField, value) != true)) {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bank", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Bank : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccNameField;
        
        private System.Nullable<double> BanMoneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private STTSoft.STTSoftService.Account AccountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccName {
            get {
                return this.AccNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccNameField, value) != true)) {
                    this.AccNameField = value;
                    this.RaisePropertyChanged("AccName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<double> BanMoney {
            get {
                return this.BanMoneyField;
            }
            set {
                if ((this.BanMoneyField.Equals(value) != true)) {
                    this.BanMoneyField = value;
                    this.RaisePropertyChanged("BanMoney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public STTSoft.STTSoftService.Account Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Discount", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Discount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AccLevelField;
        
        private System.Nullable<int> DisPercentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private STTSoft.STTSoftService.Account[] AccountsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AccLevel {
            get {
                return this.AccLevelField;
            }
            set {
                if ((this.AccLevelField.Equals(value) != true)) {
                    this.AccLevelField = value;
                    this.RaisePropertyChanged("AccLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> DisPercent {
            get {
                return this.DisPercentField;
            }
            set {
                if ((this.DisPercentField.Equals(value) != true)) {
                    this.DisPercentField = value;
                    this.RaisePropertyChanged("DisPercent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public STTSoft.STTSoftService.Account[] Accounts {
            get {
                return this.AccountsField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountsField, value) != true)) {
                    this.AccountsField = value;
                    this.RaisePropertyChanged("Accounts");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int OrIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccNameField;
        
        private System.Nullable<decimal> OrTotalField;
        
        private System.Nullable<System.DateTime> OrDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private STTSoft.STTSoftService.OrderDetail[] OrderDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private STTSoft.STTSoftService.Account AccountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OrId {
            get {
                return this.OrIdField;
            }
            set {
                if ((this.OrIdField.Equals(value) != true)) {
                    this.OrIdField = value;
                    this.RaisePropertyChanged("OrId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AccName {
            get {
                return this.AccNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccNameField, value) != true)) {
                    this.AccNameField = value;
                    this.RaisePropertyChanged("AccName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<decimal> OrTotal {
            get {
                return this.OrTotalField;
            }
            set {
                if ((this.OrTotalField.Equals(value) != true)) {
                    this.OrTotalField = value;
                    this.RaisePropertyChanged("OrTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> OrDate {
            get {
                return this.OrDateField;
            }
            set {
                if ((this.OrDateField.Equals(value) != true)) {
                    this.OrDateField = value;
                    this.RaisePropertyChanged("OrDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public STTSoft.STTSoftService.OrderDetail[] OrderDetails {
            get {
                return this.OrderDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderDetailsField, value) != true)) {
                    this.OrderDetailsField = value;
                    this.RaisePropertyChanged("OrderDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public STTSoft.STTSoftService.Account Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDetail", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OrderDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int OrdIdField;
        
        private System.Nullable<int> ProIdField;
        
        private System.Nullable<int> OrdQuantityField;
        
        private System.Nullable<int> OrIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private STTSoft.STTSoftService.Order OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private STTSoft.STTSoftService.Product ProductField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OrdId {
            get {
                return this.OrdIdField;
            }
            set {
                if ((this.OrdIdField.Equals(value) != true)) {
                    this.OrdIdField = value;
                    this.RaisePropertyChanged("OrdId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> ProId {
            get {
                return this.ProIdField;
            }
            set {
                if ((this.ProIdField.Equals(value) != true)) {
                    this.ProIdField = value;
                    this.RaisePropertyChanged("ProId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> OrdQuantity {
            get {
                return this.OrdQuantityField;
            }
            set {
                if ((this.OrdQuantityField.Equals(value) != true)) {
                    this.OrdQuantityField = value;
                    this.RaisePropertyChanged("OrdQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> OrId {
            get {
                return this.OrIdField;
            }
            set {
                if ((this.OrIdField.Equals(value) != true)) {
                    this.OrIdField = value;
                    this.RaisePropertyChanged("OrId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public STTSoft.STTSoftService.Order Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public STTSoft.STTSoftService.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProImageField;
        
        private System.Nullable<int> CatIdField;
        
        private double ProPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private STTSoft.STTSoftService.Comment[] CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private STTSoft.STTSoftService.OrderDetail[] OrderDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private STTSoft.STTSoftService.Category CategoryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProId {
            get {
                return this.ProIdField;
            }
            set {
                if ((this.ProIdField.Equals(value) != true)) {
                    this.ProIdField = value;
                    this.RaisePropertyChanged("ProId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProName {
            get {
                return this.ProNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProNameField, value) != true)) {
                    this.ProNameField = value;
                    this.RaisePropertyChanged("ProName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ProDetail {
            get {
                return this.ProDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.ProDetailField, value) != true)) {
                    this.ProDetailField = value;
                    this.RaisePropertyChanged("ProDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ProImage {
            get {
                return this.ProImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ProImageField, value) != true)) {
                    this.ProImageField = value;
                    this.RaisePropertyChanged("ProImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> CatId {
            get {
                return this.CatIdField;
            }
            set {
                if ((this.CatIdField.Equals(value) != true)) {
                    this.CatIdField = value;
                    this.RaisePropertyChanged("CatId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double ProPrice {
            get {
                return this.ProPriceField;
            }
            set {
                if ((this.ProPriceField.Equals(value) != true)) {
                    this.ProPriceField = value;
                    this.RaisePropertyChanged("ProPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public STTSoft.STTSoftService.Comment[] Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public STTSoft.STTSoftService.OrderDetail[] OrderDetails {
            get {
                return this.OrderDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderDetailsField, value) != true)) {
                    this.OrderDetailsField = value;
                    this.RaisePropertyChanged("OrderDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public STTSoft.STTSoftService.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CatIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CatNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private STTSoft.STTSoftService.Product[] ProductsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CatId {
            get {
                return this.CatIdField;
            }
            set {
                if ((this.CatIdField.Equals(value) != true)) {
                    this.CatIdField = value;
                    this.RaisePropertyChanged("CatId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CatName {
            get {
                return this.CatNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CatNameField, value) != true)) {
                    this.CatNameField = value;
                    this.RaisePropertyChanged("CatName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public STTSoft.STTSoftService.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comment", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Comment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ComIdField;
        
        private System.Nullable<int> ProIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private STTSoft.STTSoftService.Product ProductField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ComId {
            get {
                return this.ComIdField;
            }
            set {
                if ((this.ComIdField.Equals(value) != true)) {
                    this.ComIdField = value;
                    this.RaisePropertyChanged("ComId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> ProId {
            get {
                return this.ProIdField;
            }
            set {
                if ((this.ProIdField.Equals(value) != true)) {
                    this.ProIdField = value;
                    this.RaisePropertyChanged("ProId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ComContent {
            get {
                return this.ComContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ComContentField, value) != true)) {
                    this.ComContentField = value;
                    this.RaisePropertyChanged("ComContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AccName {
            get {
                return this.AccNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccNameField, value) != true)) {
                    this.AccNameField = value;
                    this.RaisePropertyChanged("AccName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public STTSoft.STTSoftService.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="STTSoftService.AdminServiceSoap")]
    public interface AdminServiceSoap {
        
        // CODEGEN: Generating message contract since element name ListUserResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListUser", ReplyAction="*")]
        STTSoft.STTSoftService.ListUserResponse ListUser(STTSoft.STTSoftService.ListUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListUser", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.ListUserRequestBody Body;
        
        public ListUserRequest() {
        }
        
        public ListUserRequest(STTSoft.STTSoftService.ListUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListUserRequestBody {
        
        public ListUserRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.ListUserResponseBody Body;
        
        public ListUserResponse() {
        }
        
        public ListUserResponse(STTSoft.STTSoftService.ListUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public STTSoft.STTSoftService.Account[] ListUserResult;
        
        public ListUserResponseBody() {
        }
        
        public ListUserResponseBody(STTSoft.STTSoftService.Account[] ListUserResult) {
            this.ListUserResult = ListUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdminServiceSoapChannel : STTSoft.STTSoftService.AdminServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceSoapClient : System.ServiceModel.ClientBase<STTSoft.STTSoftService.AdminServiceSoap>, STTSoft.STTSoftService.AdminServiceSoap {
        
        public AdminServiceSoapClient() {
        }
        
        public AdminServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STTSoft.STTSoftService.ListUserResponse STTSoft.STTSoftService.AdminServiceSoap.ListUser(STTSoft.STTSoftService.ListUserRequest request) {
            return base.Channel.ListUser(request);
        }
        
        public STTSoft.STTSoftService.Account[] ListUser() {
            STTSoft.STTSoftService.ListUserRequest inValue = new STTSoft.STTSoftService.ListUserRequest();
            inValue.Body = new STTSoft.STTSoftService.ListUserRequestBody();
            STTSoft.STTSoftService.ListUserResponse retVal = ((STTSoft.STTSoftService.AdminServiceSoap)(this)).ListUser(inValue);
            return retVal.Body.ListUserResult;
        }
    }
}
