//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STTSoft.STTSoftService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AccountDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccRoleField;
        
        private System.Nullable<int> AccLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccPassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccRole {
            get {
                return this.AccRoleField;
            }
            set {
                if ((object.ReferenceEquals(this.AccRoleField, value) != true)) {
                    this.AccRoleField = value;
                    this.RaisePropertyChanged("AccRole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<int> AccLevel {
            get {
                return this.AccLevelField;
            }
            set {
                if ((this.AccLevelField.Equals(value) != true)) {
                    this.AccLevelField = value;
                    this.RaisePropertyChanged("AccLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AccMail {
            get {
                return this.AccMailField;
            }
            set {
                if ((object.ReferenceEquals(this.AccMailField, value) != true)) {
                    this.AccMailField = value;
                    this.RaisePropertyChanged("AccMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AccPhone {
            get {
                return this.AccPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.AccPhoneField, value) != true)) {
                    this.AccPhoneField = value;
                    this.RaisePropertyChanged("AccPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AccPass {
            get {
                return this.AccPassField;
            }
            set {
                if ((object.ReferenceEquals(this.AccPassField, value) != true)) {
                    this.AccPassField = value;
                    this.RaisePropertyChanged("AccPass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AccName {
            get {
                return this.AccNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccNameField, value) != true)) {
                    this.AccNameField = value;
                    this.RaisePropertyChanged("AccName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="STTSoftService.AdminServiceSoap")]
    public interface AdminServiceSoap {
        
        // CODEGEN: Generating message contract since element name ListUserResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListUser", ReplyAction="*")]
        STTSoft.STTSoftService.ListUserResponse ListUser(STTSoft.STTSoftService.ListUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListUser", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.ListUserRequestBody Body;
        
        public ListUserRequest() {
        }
        
        public ListUserRequest(STTSoft.STTSoftService.ListUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListUserRequestBody {
        
        public ListUserRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public STTSoft.STTSoftService.ListUserResponseBody Body;
        
        public ListUserResponse() {
        }
        
        public ListUserResponse(STTSoft.STTSoftService.ListUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public STTSoft.STTSoftService.AccountDTO[] ListUserResult;
        
        public ListUserResponseBody() {
        }
        
        public ListUserResponseBody(STTSoft.STTSoftService.AccountDTO[] ListUserResult) {
            this.ListUserResult = ListUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdminServiceSoapChannel : STTSoft.STTSoftService.AdminServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceSoapClient : System.ServiceModel.ClientBase<STTSoft.STTSoftService.AdminServiceSoap>, STTSoft.STTSoftService.AdminServiceSoap {
        
        public AdminServiceSoapClient() {
        }
        
        public AdminServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STTSoft.STTSoftService.ListUserResponse STTSoft.STTSoftService.AdminServiceSoap.ListUser(STTSoft.STTSoftService.ListUserRequest request) {
            return base.Channel.ListUser(request);
        }
        
        public STTSoft.STTSoftService.AccountDTO[] ListUser() {
            STTSoft.STTSoftService.ListUserRequest inValue = new STTSoft.STTSoftService.ListUserRequest();
            inValue.Body = new STTSoft.STTSoftService.ListUserRequestBody();
            STTSoft.STTSoftService.ListUserResponse retVal = ((STTSoft.STTSoftService.AdminServiceSoap)(this)).ListUser(inValue);
            return retVal.Body.ListUserResult;
        }
    }
}
