<?xml version="1.0" encoding="utf-8"?><Database Name="STTSOFT" Class="STTSoftDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(local);Initial Catalog=STTSOFT;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="STTSOFTConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="AccName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AccRole" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AccLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AccMail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AccPhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AccPass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Account_Bank" Member="Bank" ThisKey="AccName" OtherKey="AccName" Type="Bank" Cardinality="One" />
      <Association Name="Account_Order" Member="Orders" ThisKey="AccName" OtherKey="AccName" Type="Order" />
      <Association Name="Discount_Account" Member="Discount" ThisKey="AccLevel" OtherKey="AccLevel" Type="Discount" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ProId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProDetail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProImage" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CatId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProPrice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Product_Comment" Member="Comments" ThisKey="ProId" OtherKey="ProId" Type="Comment" />
      <Association Name="Product_OrderDetail" Member="OrderDetails" ThisKey="ProId" OtherKey="ProId" Type="OrderDetail" />
      <Association Name="Category_Product" Member="Category" ThisKey="CatId" OtherKey="CatId" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bank" Member="Banks">
    <Type Name="Bank">
      <Column Name="AccName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BanMoney" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Account_Bank" Member="Account" ThisKey="AccName" OtherKey="AccName" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="CatId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CatName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Category_Product" Member="Products" ThisKey="CatId" OtherKey="CatId" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Comment" Member="Comments">
    <Type Name="Comment">
      <Column Name="ComId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ComContent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AccName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Product_Comment" Member="Product" ThisKey="ProId" OtherKey="ProId" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Discount" Member="Discounts">
    <Type Name="Discount">
      <Column Name="AccLevel" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DisPercent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Discount_Account" Member="Accounts" ThisKey="AccLevel" OtherKey="AccLevel" Type="Account" />
    </Type>
  </Table>
  <Table Name="dbo.[Order]" Member="Orders">
    <Type Name="Order">
      <Column Name="OrId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OrTotal" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="OrDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OrdSaler" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Order_OrderDetail" Member="OrderDetails" ThisKey="OrId" OtherKey="OrId" Type="OrderDetail" />
      <Association Name="Account_Order" Member="Account" ThisKey="AccName" OtherKey="AccName" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderDetail" Member="OrderDetails">
    <Type Name="OrderDetail">
      <Column Name="OrdId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrdQuantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrdTotal" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Order_OrderDetail" Member="Order" ThisKey="OrId" OtherKey="OrId" Type="Order" IsForeignKey="true" />
      <Association Name="Product_OrderDetail" Member="Product" ThisKey="ProId" OtherKey="ProId" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
</Database>